/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(1), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(2), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(2), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(2), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(3), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(4), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(4), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(5), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(5), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(5), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(5), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(5), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(5), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(5), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(5), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(5), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(5), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(5), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(5), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(5), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(5), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(5), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(5), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(5), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(5), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(5), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(5), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(6), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(7), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(8), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(8), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(9), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(9), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(9), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(9), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(10), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(10), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(10), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(11), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(11), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(12), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(13), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(13), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(13), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(13), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(14), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(14), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(15), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(15), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(16), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(16), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(17), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(17), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(17), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(17), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(17), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(18), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(19), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(19), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(19), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(20), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(20), list);
		    }
		    break;


                    case 67:
		    {
			ArrayList list = new67();
			push(goTo(20), list);
		    }
		    break;


                    case 68:
		    {
			ArrayList list = new68();
			push(goTo(21), list);
		    }
		    break;


                    case 69:
		    {
			ArrayList list = new69();
			push(goTo(21), list);
		    }
		    break;


                    case 70:
		    {
			ArrayList list = new70();
			push(goTo(21), list);
		    }
		    break;


                    case 71:
		    {
			ArrayList list = new71();
			push(goTo(21), list);
		    }
		    break;


                    case 72:
		    {
			ArrayList list = new72();
			push(goTo(22), list);
		    }
		    break;


                    case 73:
		    {
			ArrayList list = new73();
			push(goTo(22), list);
		    }
		    break;


                    case 74:
		    {
			ArrayList list = new74();
			push(goTo(23), list);
		    }
		    break;


                    case 75:
		    {
			ArrayList list = new75();
			push(goTo(24), list);
		    }
		    break;


                    case 76:
		    {
			ArrayList list = new76();
			push(goTo(24), list);
		    }
		    break;


                    case 77:
		    {
			ArrayList list = new77();
			push(goTo(25), list);
		    }
		    break;


                    case 78:
		    {
			ArrayList list = new78();
			push(goTo(25), list);
		    }
		    break;


                    case 79:
		    {
			ArrayList list = new79();
			push(goTo(26), list);
		    }
		    break;


                    case 80:
		    {
			ArrayList list = new80();
			push(goTo(26), list);
		    }
		    break;


                    case 81:
		    {
			ArrayList list = new81();
			push(goTo(27), list);
		    }
		    break;


                    case 82:
		    {
			ArrayList list = new82();
			push(goTo(27), list);
		    }
		    break;


                    case 83:
		    {
			ArrayList list = new83();
			push(goTo(28), list);
		    }
		    break;


                    case 84:
		    {
			ArrayList list = new84();
			push(goTo(28), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PProgramme node1 = (PProgramme) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PProgramme pprogrammeNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pprogrammeNode1 = new ACommandsProgramme(listNode2);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PProgramme pprogrammeNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pprogrammeNode1 = new ACommandsProgramme(listNode3);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pcommandsNode1 = new AStatementCommands(pstatementNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        PStatement pstatementNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        {
        }
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pcommandsNode1 = new AFunctionCommands(pidentifierNode2, listNode3, pstatementNode4);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        PStatement pstatementNode5;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        {
        PArgument pargumentNode3;
        pargumentNode3 = (PArgument)nodeArrayList4.get(0);
	if(pargumentNode3 != null)
	{
	  listNode4.add(pargumentNode3);
	}
        }
        pstatementNode5 = (PStatement)nodeArrayList7.get(0);

        pcommandsNode1 = new AFunctionCommands(pidentifierNode2, listNode4, pstatementNode5);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PIdentifier pidentifierNode2;
        Object nullNode3 = null;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        }

        pargumentNode1 = new AArgArgument(pidentifierNode2, null, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PIdentifier pidentifierNode2;
        PTemp2 ptemp2Node3;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        ptemp2Node3 = (PTemp2)nodeArrayList2.get(0);
        {
        }

        pargumentNode1 = new AArgArgument(pidentifierNode2, ptemp2Node3, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PIdentifier pidentifierNode2;
        Object nullNode3 = null;
        TypedLinkedList listNode5 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgArgument(pidentifierNode2, null, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PIdentifier pidentifierNode2;
        PTemp2 ptemp2Node3;
        TypedLinkedList listNode5 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        ptemp2Node3 = (PTemp2)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgArgument(pidentifierNode2, ptemp2Node3, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTemp2 ptemp2Node1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        ptemp2Node1 = new AEqValueTemp2(pvalueNode2);
        }
	nodeList.add(ptemp2Node1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTemp3 ptemp3Node1;
        {
        PIdentifier pidentifierNode2;
        Object nullNode3 = null;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);

        ptemp3Node1 = new ACommaIdTemp2Temp3(pidentifierNode2, null);
        }
	nodeList.add(ptemp3Node1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTemp3 ptemp3Node1;
        {
        PIdentifier pidentifierNode2;
        PTemp2 ptemp2Node3;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        ptemp2Node3 = (PTemp2)nodeArrayList3.get(0);

        ptemp3Node1 = new ACommaIdTemp2Temp3(pidentifierNode2, ptemp2Node3);
        }
	nodeList.add(ptemp3Node1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PMorecomparison pmorecomparisonNode2;
        PStatement pstatementNode3;
        pmorecomparisonNode2 = (PMorecomparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AIfStatement(pmorecomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PMorecomparison pmorecomparisonNode2;
        PStatement pstatementNode3;
        pmorecomparisonNode2 = (PMorecomparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(pmorecomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssigneqStatement(pidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssigneqStatement(pidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssigmpeqStatement(pidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssigmpeqStatement(pidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PMorecomparison pmorecomparisonNode2;
        PStatement pstatementNode3;
        pmorecomparisonNode2 = (PMorecomparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AWhileStatement(pmorecomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PMorecomparison pmorecomparisonNode2;
        PStatement pstatementNode3;
        pmorecomparisonNode2 = (PMorecomparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pmorecomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PIdentifier pidentifierNode3;
        PStatement pstatementNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        pidentifierNode3 = (PIdentifier)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new AForStatementStatement(pidentifierNode2, pidentifierNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PIdentifier pidentifierNode3;
        PStatement pstatementNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList3.get(0);
        pidentifierNode3 = (PIdentifier)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AForStatementStatement(pidentifierNode2, pidentifierNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PCallfuncall pcallfuncallNode2;
        pcallfuncallNode2 = (PCallfuncall)nodeArrayList1.get(0);

        pstatementNode1 = new AFuncallStatementStatement(pcallfuncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PCallfuncall pcallfuncallNode2;
        pcallfuncallNode2 = (PCallfuncall)nodeArrayList2.get(0);

        pstatementNode1 = new AFuncallStatementStatement(pcallfuncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new AListStatement(pidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pstatementNode1 = new AListStatement(pidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCallfuncall pcallfuncallNode1;
        {
        PFuncall pfuncallNode2;
        pfuncallNode2 = (PFuncall)nodeArrayList1.get(0);

        pcallfuncallNode1 = new ACallfuncalltagCallfuncall(pfuncallNode2);
        }
	nodeList.add(pcallfuncallNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFuncall pfuncallNode1;
        {
        PIdentifier pidentifierNode2;
        PFuncallt pfuncalltNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pfuncalltNode3 = (PFuncallt)nodeArrayList3.get(0);

        pfuncallNode1 = new AFuncallFuncall(pidentifierNode2, pfuncalltNode3);
        }
	nodeList.add(pfuncallNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        PFuncallt pfuncalltNode1;
        {
        Object nullNode2 = null;

        pfuncalltNode1 = new AFuncalltFuncallt(null);
        }
	nodeList.add(pfuncalltNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFuncallt pfuncalltNode1;
        {
        PArglist parglistNode2;
        parglistNode2 = (PArglist)nodeArrayList1.get(0);

        pfuncalltNode1 = new AFuncalltFuncallt(parglistNode2);
        }
	nodeList.add(pfuncalltNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);

        pexpressionNode1 = new AXppExpression(pidentifierNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);

        pexpressionNode1 = new APpxExpression(pidentifierNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pexpressionNode1 = new AListpostPrefixExpression(pidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList8 = (ArrayList) pop();
        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList3.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList5.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList8.get(0);

        pexpressionNode1 = new AListpostPrefixExpression(pidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }

        parglistNode1 = new AArglistArglist(pexpressionNode2, listNode3);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        parglistNode1 = new AArglistArglist(pexpressionNode2, listNode4);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTemp4 ptemp4Node1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        ptemp4Node1 = new ACommaExpressionTemp4(pexpressionNode2);
        }
	nodeList.add(ptemp4Node1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMorecomparison pmorecomparisonNode1;
        {
        TTrue ttrueNode2;
        ttrueNode2 = (TTrue)nodeArrayList1.get(0);

        pmorecomparisonNode1 = new ATrueMorecomparison(ttrueNode2);
        }
	nodeList.add(pmorecomparisonNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMorecomparison pmorecomparisonNode1;
        {
        TFalse tfalseNode2;
        tfalseNode2 = (TFalse)nodeArrayList1.get(0);

        pmorecomparisonNode1 = new AFalseMorecomparison(tfalseNode2);
        }
	nodeList.add(pmorecomparisonNode1);
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMorecomparison pmorecomparisonNode1;
        {
        PMorecomparison pmorecomparisonNode2;
        PMorecomparison pmorecomparisonNode3;
        pmorecomparisonNode2 = (PMorecomparison)nodeArrayList1.get(0);
        pmorecomparisonNode3 = (PMorecomparison)nodeArrayList3.get(0);

        pmorecomparisonNode1 = new AEqqormeqMorecomparison(pmorecomparisonNode2, pmorecomparisonNode3);
        }
	nodeList.add(pmorecomparisonNode1);
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMorecomparison pmorecomparisonNode1;
        pmorecomparisonNode1 = (PMorecomparison)nodeArrayList1.get(0);
	nodeList.add(pmorecomparisonNode1);
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMorecomparison pmorecomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pmorecomparisonNode1 = new AComparisonexMorecomparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pmorecomparisonNode1);
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMorecomparison pmorecomparisonNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);

        pmorecomparisonNode1 = new AIdcompMorecomparison(pexpressionNode2);
        }
	nodeList.add(pmorecomparisonNode1);
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
        {
        }

        pexpressionNode1 = new AListExpression(pvalueNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AListExpression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AArrayExpression(pidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTemp5 ptemp5Node1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        ptemp5Node1 = new ACommaValueTemp5(pvalueNode2);
        }
	nodeList.add(ptemp5Node1);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AAdditionExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ASubstractionExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultiplicationExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new67()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ADivisionExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new68()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new69()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdentifierExpression(pidentifierNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new70()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList1.get(0);

        pexpressionNode1 = new AValueExpression(pvalueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new71()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PCallfuncall pcallfuncallNode2;
        pcallfuncallNode2 = (PCallfuncall)nodeArrayList1.get(0);

        pexpressionNode1 = new AFuncallExpExpression(pcallfuncallNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new72()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        pvalueNode1 = new AStrValue(tstringNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new73()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pvalueNode1 = new ANumbValue(tnumberNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new74()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PIdentifier pidentifierNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pidentifierNode1 = new AIdIdentifier(tidNode2);
        }
	nodeList.add(pidentifierNode1);
        return nodeList;
    }



    ArrayList new75()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommands pcommandsNode1;
        pcommandsNode1 = (PCommands)nodeArrayList1.get(0);
	if(pcommandsNode1 != null)
	{
	  listNode2.add(pcommandsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new76()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommands pcommandsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommandsNode2 = (PCommands)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommandsNode2 != null)
	{
	  listNode3.add(pcommandsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new77()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PTemp3 ptemp3Node1;
        ptemp3Node1 = (PTemp3)nodeArrayList1.get(0);
	if(ptemp3Node1 != null)
	{
	  listNode2.add(ptemp3Node1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new78()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PTemp3 ptemp3Node2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ptemp3Node2 = (PTemp3)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ptemp3Node2 != null)
	{
	  listNode3.add(ptemp3Node2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new79()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new80()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new81()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PTemp4 ptemp4Node1;
        ptemp4Node1 = (PTemp4)nodeArrayList1.get(0);
	if(ptemp4Node1 != null)
	{
	  listNode2.add(ptemp4Node1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new82()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PTemp4 ptemp4Node2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ptemp4Node2 = (PTemp4)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ptemp4Node2 != null)
	{
	  listNode3.add(ptemp4Node2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new83()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PTemp5 ptemp5Node1;
        ptemp5Node1 = (PTemp5)nodeArrayList1.get(0);
	if(ptemp5Node1 != null)
	{
	  listNode2.add(ptemp5Node1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new84()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PTemp5 ptemp5Node2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ptemp5Node2 = (PTemp5)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ptemp5Node2 != null)
	{
	  listNode3.add(ptemp5Node2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {17, SHIFT, 2}, {26, SHIFT, 3}, {29, SHIFT, 4}, {30, SHIFT, 5}, {31, SHIFT, 6}, {32, SHIFT, 7}, {40, SHIFT, 8}, },
			{{-1, REDUCE, 79}, },
			{{-1, ERROR, 2}, {40, SHIFT, 8}, },
			{{-1, ERROR, 3}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {35, SHIFT, 21}, {37, SHIFT, 22}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 4}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {35, SHIFT, 21}, {37, SHIFT, 22}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 5}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 6}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 7}, {40, SHIFT, 8}, },
			{{-1, REDUCE, 74}, },
			{{-1, ERROR, 9}, {42, ACCEPT, -1}, },
			{{-1, REDUCE, 75}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 28}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 14}, {4, SHIFT, 40}, {5, SHIFT, 41}, {6, SHIFT, 42}, {14, SHIFT, 43}, {19, SHIFT, 44}, {21, SHIFT, 45}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {17, SHIFT, 2}, {26, SHIFT, 3}, {29, SHIFT, 4}, {30, SHIFT, 5}, {31, SHIFT, 6}, {32, SHIFT, 7}, {40, SHIFT, 8}, },
			{{-1, ERROR, 16}, {0, SHIFT, 48}, {26, SHIFT, 49}, {29, SHIFT, 50}, {30, SHIFT, 51}, {31, SHIFT, 52}, {32, SHIFT, 53}, {40, SHIFT, 8}, },
			{{-1, ERROR, 17}, {19, SHIFT, 56}, },
			{{-1, ERROR, 18}, {0, SHIFT, 1}, {40, SHIFT, 8}, },
			{{-1, ERROR, 19}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 20}, {39, SHIFT, 23}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 73}, },
			{{-1, REDUCE, 72}, },
			{{-1, REDUCE, 71}, },
			{{-1, REDUCE, 59}, },
			{{-1, ERROR, 27}, {36, SHIFT, 61}, },
			{{-1, REDUCE, 49}, {33, SHIFT, 62}, {34, SHIFT, 63}, },
			{{-1, ERROR, 29}, {3, SHIFT, 65}, {9, SHIFT, 66}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 51}, {1, SHIFT, 68}, {3, REDUCE, 62}, {9, REDUCE, 62}, {10, SHIFT, 69}, {11, SHIFT, 70}, {13, SHIFT, 71}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 70}, },
			{{-1, REDUCE, 69}, {2, SHIFT, 72}, {19, SHIFT, 44}, {21, SHIFT, 73}, },
			{{-1, ERROR, 35}, {36, SHIFT, 74}, },
			{{-1, REDUCE, 18}, {23, SHIFT, 75}, },
			{{-1, REDUCE, 62}, {1, SHIFT, 68}, {10, SHIFT, 69}, {11, SHIFT, 70}, {13, SHIFT, 71}, },
			{{-1, REDUCE, 26}, },
			{{-1, ERROR, 39}, {7, SHIFT, 78}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 41}, },
			{{-1, REDUCE, 42}, },
			{{-1, ERROR, 43}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 34}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 45}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 46}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 76}, },
			{{-1, REDUCE, 80}, },
			{{-1, ERROR, 49}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {35, SHIFT, 21}, {37, SHIFT, 22}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 50}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {35, SHIFT, 21}, {37, SHIFT, 22}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 51}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 52}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 53}, {40, SHIFT, 8}, },
			{{-1, REDUCE, 29}, },
			{{-1, ERROR, 55}, {4, SHIFT, 40}, {5, SHIFT, 41}, {6, SHIFT, 42}, {14, SHIFT, 90}, {19, SHIFT, 44}, {21, SHIFT, 91}, },
			{{-1, ERROR, 56}, {20, SHIFT, 93}, {40, SHIFT, 8}, },
			{{-1, REDUCE, 37}, {21, SHIFT, 96}, },
			{{-1, ERROR, 58}, {0, SHIFT, 48}, {40, SHIFT, 8}, },
			{{-1, ERROR, 59}, {20, SHIFT, 98}, },
			{{-1, ERROR, 60}, {22, SHIFT, 99}, {23, SHIFT, 100}, },
			{{-1, ERROR, 61}, {0, SHIFT, 1}, {26, SHIFT, 3}, {29, SHIFT, 4}, {30, SHIFT, 5}, {31, SHIFT, 6}, {32, SHIFT, 7}, {40, SHIFT, 8}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 55}, },
			{{-1, ERROR, 64}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 53}, },
			{{-1, ERROR, 67}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 68}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 69}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 70}, {19, SHIFT, 19}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 71}, {19, SHIFT, 19}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 36}, },
			{{-1, ERROR, 73}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 74}, {0, SHIFT, 1}, {26, SHIFT, 3}, {29, SHIFT, 4}, {30, SHIFT, 5}, {31, SHIFT, 6}, {32, SHIFT, 7}, {40, SHIFT, 8}, },
			{{-1, ERROR, 75}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 81}, },
			{{-1, REDUCE, 20}, {23, SHIFT, 75}, },
			{{-1, ERROR, 78}, {40, SHIFT, 8}, },
			{{-1, REDUCE, 14}, },
			{{-1, ERROR, 80}, {20, SHIFT, 116}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 43}, {23, SHIFT, 75}, },
			{{-1, ERROR, 83}, {22, SHIFT, 118}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 85}, {36, SHIFT, 119}, },
			{{-1, ERROR, 86}, {36, SHIFT, 120}, },
			{{-1, REDUCE, 19}, {23, SHIFT, 75}, },
			{{-1, REDUCE, 27}, },
			{{-1, ERROR, 89}, {7, SHIFT, 122}, },
			{{-1, ERROR, 90}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 91}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 92}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 93}, {36, SHIFT, 126}, },
			{{-1, ERROR, 94}, {20, SHIFT, 127}, },
			{{-1, REDUCE, 5}, {14, SHIFT, 128}, {23, SHIFT, 129}, },
			{{-1, ERROR, 96}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 97}, {21, SHIFT, 134}, },
			{{-1, REDUCE, 68}, },
			{{-1, REDUCE, 57}, },
			{{-1, ERROR, 100}, {39, SHIFT, 23}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 83}, },
			{{-1, ERROR, 102}, {22, SHIFT, 136}, {23, SHIFT, 100}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 50}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 64}, },
			{{-1, REDUCE, 66}, },
			{{-1, REDUCE, 69}, {19, SHIFT, 44}, },
			{{-1, REDUCE, 67}, },
			{{-1, ERROR, 111}, {22, SHIFT, 138}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 82}, },
			{{-1, ERROR, 115}, {36, SHIFT, 139}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 44}, {23, SHIFT, 75}, },
			{{-1, ERROR, 118}, {14, SHIFT, 140}, },
			{{-1, ERROR, 119}, {0, SHIFT, 1}, {26, SHIFT, 3}, {29, SHIFT, 4}, {30, SHIFT, 5}, {31, SHIFT, 6}, {32, SHIFT, 7}, {40, SHIFT, 8}, },
			{{-1, ERROR, 120}, {0, SHIFT, 1}, {26, SHIFT, 3}, {29, SHIFT, 4}, {30, SHIFT, 5}, {31, SHIFT, 6}, {32, SHIFT, 7}, {40, SHIFT, 8}, },
			{{-1, REDUCE, 21}, {23, SHIFT, 75}, },
			{{-1, ERROR, 122}, {40, SHIFT, 8}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 124}, {22, SHIFT, 144}, },
			{{-1, REDUCE, 17}, },
			{{-1, ERROR, 126}, {0, SHIFT, 1}, {26, SHIFT, 3}, {29, SHIFT, 4}, {30, SHIFT, 5}, {31, SHIFT, 6}, {32, SHIFT, 7}, {40, SHIFT, 8}, },
			{{-1, ERROR, 127}, {36, SHIFT, 146}, },
			{{-1, ERROR, 128}, {39, SHIFT, 23}, {41, SHIFT, 24}, },
			{{-1, ERROR, 129}, {40, SHIFT, 8}, },
			{{-1, REDUCE, 6}, {23, SHIFT, 129}, },
			{{-1, REDUCE, 77}, },
			{{-1, REDUCE, 7}, {23, SHIFT, 129}, },
			{{-1, ERROR, 133}, {22, SHIFT, 151}, },
			{{-1, ERROR, 134}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 61}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 84}, },
			{{-1, REDUCE, 60}, },
			{{-1, ERROR, 139}, {0, SHIFT, 1}, {26, SHIFT, 3}, {29, SHIFT, 4}, {30, SHIFT, 5}, {31, SHIFT, 6}, {32, SHIFT, 7}, {40, SHIFT, 8}, },
			{{-1, ERROR, 140}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 23}, },
			{{-1, ERROR, 143}, {36, SHIFT, 155}, },
			{{-1, ERROR, 144}, {14, SHIFT, 156}, },
			{{-1, REDUCE, 3}, },
			{{-1, ERROR, 146}, {0, SHIFT, 1}, {26, SHIFT, 3}, {29, SHIFT, 4}, {30, SHIFT, 5}, {31, SHIFT, 6}, {32, SHIFT, 7}, {40, SHIFT, 8}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 10}, {14, SHIFT, 128}, },
			{{-1, REDUCE, 8}, {23, SHIFT, 129}, },
			{{-1, REDUCE, 78}, },
			{{-1, ERROR, 151}, {14, SHIFT, 159}, },
			{{-1, ERROR, 152}, {22, SHIFT, 160}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 155}, {0, SHIFT, 1}, {26, SHIFT, 3}, {29, SHIFT, 4}, {30, SHIFT, 5}, {31, SHIFT, 6}, {32, SHIFT, 7}, {40, SHIFT, 8}, },
			{{-1, ERROR, 156}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 159}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, ERROR, 160}, {14, SHIFT, 164}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 164}, {2, SHIFT, 18}, {19, SHIFT, 19}, {21, SHIFT, 20}, {39, SHIFT, 23}, {40, SHIFT, 8}, {41, SHIFT, 24}, },
			{{-1, REDUCE, 39}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 9}, },
			{{-1, 10}, {15, 47}, },
			{{-1, 94}, },
			{{-1, 130}, {148, 158}, },
			{{-1, 131}, {132, 150}, {149, 150}, },
			{{-1, 11}, {61, 103}, {74, 112}, {119, 141}, {120, 142}, {126, 145}, {139, 153}, {146, 157}, {155, 161}, },
			{{-1, 25}, {0, 12}, {15, 12}, {16, 54}, {61, 12}, {74, 12}, {119, 12}, {120, 12}, {126, 12}, {139, 12}, {146, 12}, {155, 12}, },
			{{-1, 13}, },
			{{-1, 80}, },
			{{-1, 26}, },
			{{-1, 46}, {55, 92}, },
			{{-1, 81}, },
			{{-1, 76}, {77, 114}, {117, 114}, {121, 114}, },
			{{-1, 27}, {4, 35}, {49, 85}, {50, 86}, },
			{{-1, 28}, {64, 104}, },
			{{-1, 67}, },
			{{-1, 64}, },
			{{-1, 29}, {5, 36}, {6, 38}, {19, 59}, {43, 79}, {44, 82}, {45, 83}, {46, 84}, {51, 87}, {52, 88}, {67, 105}, {68, 106}, {69, 107}, {73, 111}, {75, 113}, {90, 123}, {91, 124}, {92, 125}, {96, 133}, {134, 152}, {140, 154}, {156, 162}, {159, 163}, {164, 165}, },
			{{-1, 101}, {102, 137}, },
			{{-1, 30}, },
			{{-1, 37}, {3, 31}, {4, 31}, {49, 31}, {50, 31}, {64, 31}, },
			{{-1, 32}, {70, 108}, {71, 110}, },
			{{-1, 33}, {20, 60}, {100, 135}, {128, 147}, },
			{{-1, 34}, {0, 14}, {2, 17}, {7, 39}, {15, 14}, {16, 55}, {18, 57}, {53, 89}, {56, 95}, {58, 97}, {61, 14}, {70, 109}, {71, 109}, {74, 14}, {78, 115}, {119, 14}, {120, 14}, {122, 143}, {126, 14}, {129, 148}, {139, 14}, {146, 14}, {155, 14}, },
			{{-1, 15}, },
			{{-1, 132}, {130, 149}, },
			{{-1, 16}, {18, 58}, },
			{{-1, 77}, {82, 117}, {87, 121}, },
			{{-1, 102}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: tab, 'def', 'if', 'while', 'print', 'return', 'for', id, EOF",
			"expecting: tab, 'if', 'while', 'print', 'return', 'for', id",
			"expecting: id",
			"expecting: pp, '(', '[', 'true', 'false', number, id, string",
			"expecting: pp, '(', '[', number, id, string",
			"expecting: tab, '+', pp, '==', '-=', '+=', '/=', 'in', '!=', '-', '*', '/', '=', 'def', '(', ')', '[', ']', ',', 'if', 'while', 'print', 'return', 'for', '<', '>', ':', id, EOF",
			"expecting: EOF",
			"expecting: tab, '+', '==', '!=', '-', '*', '/', 'def', ')', ']', ',', 'if', 'while', 'print', 'return', 'for', '<', '>', ':', id, EOF",
			"expecting: '-=', '+=', '/=', '=', '(', '['",
			"expecting: '('",
			"expecting: tab, id",
			"expecting: number, string",
			"expecting: ':'",
			"expecting: tab, '==', '!=', 'def', ')', ']', ',', 'if', 'while', 'print', 'return', 'for', '<', '>', ':', id, EOF",
			"expecting: '<', '>', ':'",
			"expecting: '==', '!='",
			"expecting: '+', '==', '!=', '-', '*', '/', '<', '>', ':'",
			"expecting: tab, '+', pp, '==', '!=', '-', '*', '/', 'def', '(', ')', '[', ']', ',', 'if', 'while', 'print', 'return', 'for', '<', '>', ':', id, EOF",
			"expecting: tab, 'def', ',', 'if', 'while', 'print', 'return', 'for', id, EOF",
			"expecting: 'in'",
			"expecting: pp, '(', ')', '[', number, id, string",
			"expecting: ')', id",
			"expecting: tab, '==', '!=', 'def', ')', '[', ']', ',', 'if', 'while', 'print', 'return', 'for', '<', '>', ':', id, EOF",
			"expecting: ')'",
			"expecting: ']', ','",
			"expecting: '(', number, id, string",
			"expecting: tab, 'def', ')', ',', 'if', 'while', 'print', 'return', 'for', id, EOF",
			"expecting: ')', ','",
			"expecting: ']'",
			"expecting: '=', ')', ','",
			"expecting: '['",
			"expecting: tab, '+', '==', '!=', '-', '*', '/', 'def', '(', ')', ']', ',', 'if', 'while', 'print', 'return', 'for', '<', '>', ':', id, EOF",
			"expecting: '='",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 4, 4, 2, 5, 6, 0, 0, 0, 7, 8, 0, 1, 9, 10, 4, 11, 12, 12, 7, 7, 7, 13, 12, 14, 15, 13, 16, 7, 7, 17, 12, 18, 7, 0, 19, 4, 4, 4, 4, 20, 4, 4, 0, 1, 3, 3, 4, 4, 2, 0, 8, 21, 22, 10, 23, 24, 1, 4, 4, 4, 4, 4, 4, 4, 4, 25, 25, 13, 4, 1, 4, 26, 18, 2, 0, 23, 23, 27, 28, 0, 12, 12, 18, 0, 19, 4, 4, 4, 12, 23, 29, 4, 30, 7, 13, 11, 24, 24, 0, 12, 14, 13, 13, 7, 31, 7, 28, 0, 26, 26, 12, 7, 27, 32, 1, 1, 18, 2, 0, 28, 0, 1, 12, 11, 2, 27, 27, 27, 28, 4, 24, 13, 24, 13, 1, 4, 0, 0, 12, 32, 0, 1, 27, 29, 27, 27, 32, 28, 0, 0, 1, 4, 0, 27, 4, 32, 0, 0, 13, 4, 13, 
        };*/
}
