/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.node.*;
import minipython.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTTab(TTab node)
    {
        index = 0;
    }

    public void caseTPlus(TPlus node)
    {
        index = 1;
    }

    public void caseTPp(TPp node)
    {
        index = 2;
    }

    public void caseTEqq(TEqq node)
    {
        index = 3;
    }

    public void caseTMinuseq(TMinuseq node)
    {
        index = 4;
    }

    public void caseTPluseq(TPluseq node)
    {
        index = 5;
    }

    public void caseTDeq(TDeq node)
    {
        index = 6;
    }

    public void caseTIn(TIn node)
    {
        index = 7;
    }

    public void caseTRange(TRange node)
    {
        index = 8;
    }

    public void caseTNeqq(TNeqq node)
    {
        index = 9;
    }

    public void caseTMinus(TMinus node)
    {
        index = 10;
    }

    public void caseTMult(TMult node)
    {
        index = 11;
    }

    public void caseTDmult(TDmult node)
    {
        index = 12;
    }

    public void caseTDiv(TDiv node)
    {
        index = 13;
    }

    public void caseTEq(TEq node)
    {
        index = 14;
    }

    public void caseTExclam(TExclam node)
    {
        index = 15;
    }

    public void caseTDictt(TDictt node)
    {
        index = 16;
    }

    public void caseTDef(TDef node)
    {
        index = 17;
    }

    public void caseTLogicPlus(TLogicPlus node)
    {
        index = 18;
    }

    public void caseTLPar(TLPar node)
    {
        index = 19;
    }

    public void caseTRPar(TRPar node)
    {
        index = 20;
    }

    public void caseTLBr(TLBr node)
    {
        index = 21;
    }

    public void caseTRBr(TRBr node)
    {
        index = 22;
    }

    public void caseTComma(TComma node)
    {
        index = 23;
    }

    public void caseTQmark(TQmark node)
    {
        index = 24;
    }

    public void caseTGqmark(TGqmark node)
    {
        index = 25;
    }

    public void caseTIf(TIf node)
    {
        index = 26;
    }

    public void caseTElif(TElif node)
    {
        index = 27;
    }

    public void caseTElse(TElse node)
    {
        index = 28;
    }

    public void caseTWhile(TWhile node)
    {
        index = 29;
    }

    public void caseTPrint(TPrint node)
    {
        index = 30;
    }

    public void caseTReturn(TReturn node)
    {
        index = 31;
    }

    public void caseTFor(TFor node)
    {
        index = 32;
    }

    public void caseTLess(TLess node)
    {
        index = 33;
    }

    public void caseTGreat(TGreat node)
    {
        index = 34;
    }

    public void caseTTrue(TTrue node)
    {
        index = 35;
    }

    public void caseTSemi(TSemi node)
    {
        index = 36;
    }

    public void caseTFalse(TFalse node)
    {
        index = 37;
    }

    public void caseTQuote(TQuote node)
    {
        index = 38;
    }

    public void caseTNumber(TNumber node)
    {
        index = 39;
    }

    public void caseTId(TId node)
    {
        index = 40;
    }

    public void caseTString(TString node)
    {
        index = 41;
    }

    public void caseEOF(EOF node)
    {
        index = 42;
    }
}
