/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AArglistArglist extends PArglist
{
    private PExpression _expression_;
    private final LinkedList _temp4_ = new TypedLinkedList(new Temp4_Cast());

    public AArglistArglist()
    {
    }

    public AArglistArglist(
        PExpression _expression_,
        List _temp4_)
    {
        setExpression(_expression_);

        {
            this._temp4_.clear();
            this._temp4_.addAll(_temp4_);
        }

    }
    public Object clone()
    {
        return new AArglistArglist(
            (PExpression) cloneNode(_expression_),
            cloneList(_temp4_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArglistArglist(this);
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public LinkedList getTemp4()
    {
        return _temp4_;
    }

    public void setTemp4(List list)
    {
        _temp4_.clear();
        _temp4_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_expression_)
            + toString(_temp4_);
    }

    void removeChild(Node child)
    {
        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_temp4_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator i = _temp4_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Temp4_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PTemp4 node = (PTemp4) o;

            if((node.parent() != null) &&
                (node.parent() != AArglistArglist.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AArglistArglist.this))
            {
                node.parent(AArglistArglist.this);
            }

            return node;
        }
    }
}
