/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AArrayExpression extends PExpression
{
    private PIdentifier _identifier_;
    private PExpression _leftexpr_;

    public AArrayExpression()
    {
    }

    public AArrayExpression(
        PIdentifier _identifier_,
        PExpression _leftexpr_)
    {
        setIdentifier(_identifier_);

        setLeftexpr(_leftexpr_);

    }
    public Object clone()
    {
        return new AArrayExpression(
            (PIdentifier) cloneNode(_identifier_),
            (PExpression) cloneNode(_leftexpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayExpression(this);
    }

    public PIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(PIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public PExpression getLeftexpr()
    {
        return _leftexpr_;
    }

    public void setLeftexpr(PExpression node)
    {
        if(_leftexpr_ != null)
        {
            _leftexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _leftexpr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_leftexpr_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_leftexpr_ == child)
        {
            _leftexpr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((PIdentifier) newChild);
            return;
        }

        if(_leftexpr_ == oldChild)
        {
            setLeftexpr((PExpression) newChild);
            return;
        }

    }
}
