/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFalseBoolean extends PBoolean
{

    public AFalseBoolean()
    {
    }
    public Object clone()
    {
        return new AFalseBoolean();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFalseBoolean(this);
    }

    public String toString()
    {
        return "";
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }
}
