/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFuncalltFuncallt extends PFuncallt
{
    private PArglist _arglist_;

    public AFuncalltFuncallt()
    {
    }

    public AFuncalltFuncallt(
        PArglist _arglist_)
    {
        setArglist(_arglist_);

    }
    public Object clone()
    {
        return new AFuncalltFuncallt(
            (PArglist) cloneNode(_arglist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncalltFuncallt(this);
    }

    public PArglist getArglist()
    {
        return _arglist_;
    }

    public void setArglist(PArglist node)
    {
        if(_arglist_ != null)
        {
            _arglist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _arglist_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_arglist_);
    }

    void removeChild(Node child)
    {
        if(_arglist_ == child)
        {
            _arglist_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_arglist_ == oldChild)
        {
            setArglist((PArglist) newChild);
            return;
        }

    }
}
