/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFuncallFuncall extends PFuncall
{
    private PIdentifier _identifier_;
    private PFuncallt _funcallt_;

    public AFuncallFuncall()
    {
    }

    public AFuncallFuncall(
        PIdentifier _identifier_,
        PFuncallt _funcallt_)
    {
        setIdentifier(_identifier_);

        setFuncallt(_funcallt_);

    }
    public Object clone()
    {
        return new AFuncallFuncall(
            (PIdentifier) cloneNode(_identifier_),
            (PFuncallt) cloneNode(_funcallt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncallFuncall(this);
    }

    public PIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(PIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public PFuncallt getFuncallt()
    {
        return _funcallt_;
    }

    public void setFuncallt(PFuncallt node)
    {
        if(_funcallt_ != null)
        {
            _funcallt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _funcallt_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_funcallt_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_funcallt_ == child)
        {
            _funcallt_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((PIdentifier) newChild);
            return;
        }

        if(_funcallt_ == oldChild)
        {
            setFuncallt((PFuncallt) newChild);
            return;
        }

    }
}
