/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AListExpression extends PExpression
{
    private PValue _value_;
    private final LinkedList _temp5_ = new TypedLinkedList(new Temp5_Cast());

    public AListExpression()
    {
    }

    public AListExpression(
        PValue _value_,
        List _temp5_)
    {
        setValue(_value_);

        {
            this._temp5_.clear();
            this._temp5_.addAll(_temp5_);
        }

    }
    public Object clone()
    {
        return new AListExpression(
            (PValue) cloneNode(_value_),
            cloneList(_temp5_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListExpression(this);
    }

    public PValue getValue()
    {
        return _value_;
    }

    public void setValue(PValue node)
    {
        if(_value_ != null)
        {
            _value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _value_ = node;
    }

    public LinkedList getTemp5()
    {
        return _temp5_;
    }

    public void setTemp5(List list)
    {
        _temp5_.clear();
        _temp5_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_value_)
            + toString(_temp5_);
    }

    void removeChild(Node child)
    {
        if(_value_ == child)
        {
            _value_ = null;
            return;
        }

        if(_temp5_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator i = _temp5_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Temp5_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PTemp5 node = (PTemp5) o;

            if((node.parent() != null) &&
                (node.parent() != AListExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AListExpression.this))
            {
                node.parent(AListExpression.this);
            }

            return node;
        }
    }
}
