/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TDeq extends Token
{
    public TDeq()
    {
        super.setText("/=");
    }

    public TDeq(int line, int pos)
    {
        super.setText("/=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDeq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDeq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDeq text.");
    }
}
