/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TEqq extends Token
{
    public TEqq()
    {
        super.setText("==");
    }

    public TEqq(int line, int pos)
    {
        super.setText("==");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TEqq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEqq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TEqq text.");
    }
}
