/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TMinuseq extends Token
{
    public TMinuseq()
    {
        super.setText("-=");
    }

    public TMinuseq(int line, int pos)
    {
        super.setText("-=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMinuseq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMinuseq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMinuseq text.");
    }
}
