/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TNeqq extends Token
{
    public TNeqq()
    {
        super.setText("!=");
    }

    public TNeqq(int line, int pos)
    {
        super.setText("!=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNeqq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNeqq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNeqq text.");
    }
}
